/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.Reader;
import java.io.StringReader;
import java.nio.file.Files;
import java.util.logging.Level;
import java.util.logging.Logger;
import java_cup.runtime.Scanner;
import java_cup.runtime.Symbol;
import javax.swing.JFileChooser;

/**
 *
 * @author Dennis
 */
public class AnalizarTexto extends javax.swing.JFrame {

    /**
     * Creates new form Texto
     */
    public AnalizarTexto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_abrir_archivo = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSalida_lexico = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_codigo_fuente = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtSalida_sintactico = new javax.swing.JTextArea();
        btn_sintactico = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        TXT_HTML = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_abrir_archivo.setText("Abrir archivo");
        btn_abrir_archivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_abrir_archivoActionPerformed(evt);
            }
        });

        btn_limpiar.setText("Limpiar");
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        txtSalida_lexico.setColumns(20);
        txtSalida_lexico.setRows(5);
        jScrollPane1.setViewportView(txtSalida_lexico);

        txt_codigo_fuente.setColumns(20);
        txt_codigo_fuente.setRows(5);
        jScrollPane2.setViewportView(txt_codigo_fuente);

        txtSalida_sintactico.setColumns(20);
        txtSalida_sintactico.setRows(5);
        jScrollPane3.setViewportView(txtSalida_sintactico);

        btn_sintactico.setText("Sintactico");
        btn_sintactico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sintacticoActionPerformed(evt);
            }
        });

        TXT_HTML.setColumns(20);
        TXT_HTML.setRows(5);
        jScrollPane4.setViewportView(TXT_HTML);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sintactico, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_abrir_archivo, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(btn_abrir_archivo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(btn_sintactico, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 43, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        // TODO add your handling code here:
        //txtEntrada.setText("");
        txtSalida_lexico.setText("");
        txtSalida_sintactico.setText("");
        txt_codigo_fuente.setText("");


    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void btn_abrir_archivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_abrir_archivoActionPerformed
        // TODO add your handling code here:

        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File archivo = new File(chooser.getSelectedFile().getAbsolutePath());

        try {

            String ST = new String(Files.readAllBytes(archivo.toPath()));
            txt_codigo_fuente.setText(ST);

        } catch (FileNotFoundException ex) {
            Logger.getLogger(AnalizarTexto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(AnalizarTexto.class.getName()).log(Level.SEVERE, null, ex);
        }

        JFileChooser chooser2 = new JFileChooser();
        chooser.showOpenDialog(null);
        try {
            Reader escaner = new BufferedReader(new FileReader(chooser.getSelectedFile()));
            Lexer lexico = new Lexer(escaner);
            String resultado = "";

            while (true) {
                Tokens tokens = lexico.yylex();
                if (tokens == null) {
                    resultado += "EOFF";
                    txtSalida_lexico.setText(resultado);
                }
                switch (tokens) {
                    case Error:
                        resultado += lexico.yytext() + "\t Error lexico: simbolo no encontrado";
                    case CADENA_NO_ESPECIFICA:
                    case COLUMNA:
                    case CORREO_ELECTRONICO:
                    case ENLACE_WEB:
                    case FILA_INICIO:
                    case FINAL_ENCABEZADO:
                    case FINAL_FILA:
                    case FINAL_HTML:
                    case FINAL_TABLA:
                    case FIN_IMAGEN:
                    case INICIO_CUERPO:
                    case INICIO_ENCABEZADO:
                    case INICIO_HTML:
                    case INICIO_IMAGEN:
                    case INICIO_LISTA:
                    case INICIO_TABLA:
                    case MEDIDA_ALTURA:
                    case MEDIDA_ANCHO:
                    case NOMBRE_ELEMENTO:
                    case NUMERO_DECIMAL:
                    case NUMERO_ENTERO:
                    case PARENTESIS_APERTURA:
                    case PARENTESIS_CIERRE:
                    case SALIDA_TEXTO:
                    case TEXTO_FUERTE:
                    case TITULO:
                    case BORDE_TABLA:
                    case FINAL_CUERPO:
                    case FINAL_IMAGEN:
                    case FINAL_LISTA:
                    case FINAL_TITULO:
                    case PUNTO_COMA:
                    case SIGNO_IGUAL:
                    case SIGNO_MULTIPLICACION:
                    case SIGNO_RESTA:
                    case SIGNO_SUMA:
                    case Comilla:
                    case COMA:
                    case DOS_PUNTOS:
                    case URL:
                    case COLUMNA_FIN:
                    case SALTO_LINEA:
                    case FINAL_DIALOGO:
                    case FINAL_PARRAFO:
                    case INICIO_DIALOGO:
                    case INICIO_PARRAFO:
                    case FINAL_ELEMENTO_LISTA:
                    case FINAL_ETIQUETA:
                    case FINAL_MENU:
                    case INICIO_ELEMENTO_LISTA:
                    case INICIO_ETIQUETA:
                    case INICIO_MENU:
                    case LINEA_DIVISORA:

                        resultado += lexico.Lexeme + "\t\t Es un \t" + tokens + "\n";
                    default:
                        resultado += "\t\t Token identificado " + tokens + "\n";
                }
            }
        } catch (FileNotFoundException ex) {
            ex.printStackTrace(System.out);
        } catch (IOException ex) {
            ex.printStackTrace(System.out);
        }


    }//GEN-LAST:event_btn_abrir_archivoActionPerformed

    private void btn_sintacticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sintacticoActionPerformed
        // TODO add your handling code here:
        String ST = txt_codigo_fuente.getText();
        Sintax s = new Sintax(new codigo.LexerCup(new StringReader(ST)));

        Lexer lexico = new Lexer(new BufferedReader(new StringReader(txt_codigo_fuente.getText())));
        String resultado = "";
        
        try {
            s.parse();
            TXT_HTML.setText(s.resultado);
            txtSalida_sintactico.setText("ANALISIS SINTACTICO CORRECTO");
            
        } catch (Exception e) {
            e.getMessage();
        }

        /*
        try {
            s.parse();
            txtSalida_sintactico.setText("Analisis realizado correctamente");
            TXT_HTML.setText(resultado);
            txtSalida_sintactico.setForeground(new Color(25, 111, 61));
        } catch (Exception ex) {
            Symbol sym = s.getS();
            txtSalida_sintactico.setText("Error de sintaxis. Linea " + (sym.right + 1) + " Columna: " + (sym.left + 1) + ", Texto: \"" + sym.value + "\"");
            txtSalida_sintactico.setForeground(Color.red);
        }
         */
    }//GEN-LAST:event_btn_sintacticoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnalizarTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnalizarTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnalizarTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnalizarTexto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnalizarTexto().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TXT_HTML;
    private javax.swing.JButton btn_abrir_archivo;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_sintactico;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea txtSalida_lexico;
    private javax.swing.JTextArea txtSalida_sintactico;
    private javax.swing.JTextArea txt_codigo_fuente;
    // End of variables declaration//GEN-END:variables
}
