package codigo;


//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------



/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int FINAL_HTML = 22;
  public static final int FINAL_TITULO = 5;
  public static final int ENLACE_WEB = 16;
  public static final int PARENTESIS_CIERRE = 33;
  public static final int FINAL_ELEMENTO_LISTA = 50;
  public static final int LINEA_DIVISORA = 41;
  public static final int SIGNO_RESTA = 36;
  public static final int INICO_DIALOGO = 45;
  public static final int DOS_PUNTOS = 39;
  public static final int MEDIDA_ALTURA = 20;
  public static final int INICIO_IMAGEN = 17;
  public static final int BORDE_TABLA = 23;
  public static final int SIGNO_SUMA = 35;
  public static final int INICIO_HTML = 2;
  public static final int SIGNO_IGUAL = 38;
  public static final int FILA_INICIO = 9;
  public static final int FINAL_ENCABEZADO = 6;
  public static final int TITULO = 4;
  public static final int FINAL_MENU = 52;
  public static final int SALIDA_TEXTO = 14;
  public static final int FINAL_IMAGEN = 21;
  public static final int TEXTO_FUERTE = 13;
  public static final int CADENA_NO_ESPECIFICA = 29;
  public static final int PUNTO_COMA = 37;
  public static final int SIGNO_MULTIPLICACION = 34;
  public static final int INICIO_ETIQUETA = 42;
  public static final int MEDIDA_ANCHO = 19;
  public static final int EOF = 0;
  public static final int INICIO_LISTA = 15;
  public static final int FINAL_PARRAFO = 48;
  public static final int INICIO_PARRAFO = 47;
  public static final int error = 1;
  public static final int COMA = 40;
  public static final int URL = 31;
  public static final int INICIO_TABLA = 7;
  public static final int INICIO_MENU = 51;
  public static final int NOMBRE_ELEMENTO = 18;
  public static final int INICIO_CUERPO = 8;
  public static final int FINAL_LISTA = 25;
  public static final int INICIO_ELEMENTO_LISTA = 49;
  public static final int INICIO_ENCABEZADO = 3;
  public static final int CORREO_ELECTRONICO = 28;
  public static final int FINAL_ETIQUETA = 43;
  public static final int FINAL_TABLA = 12;
  public static final int SALTO_LINEA = 44;
  public static final int FINAL_DIALOGO = 46;
  public static final int FINAL_CUERPO = 24;
  public static final int PARENTESIS_APERTURA = 32;
  public static final int NMERO_DECIMAL = 27;
  public static final int FINAL_FILA = 10;
  public static final int NUMERO_ENTERO = 26;
  public static final int Comilla = 30;
  public static final int COLUMNA = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INICIO_HTML",
  "INICIO_ENCABEZADO",
  "TITULO",
  "FINAL_TITULO",
  "FINAL_ENCABEZADO",
  "INICIO_TABLA",
  "INICIO_CUERPO",
  "FILA_INICIO",
  "FINAL_FILA",
  "COLUMNA",
  "FINAL_TABLA",
  "TEXTO_FUERTE",
  "SALIDA_TEXTO",
  "INICIO_LISTA",
  "ENLACE_WEB",
  "INICIO_IMAGEN",
  "NOMBRE_ELEMENTO",
  "MEDIDA_ANCHO",
  "MEDIDA_ALTURA",
  "FINAL_IMAGEN",
  "FINAL_HTML",
  "BORDE_TABLA",
  "FINAL_CUERPO",
  "FINAL_LISTA",
  "NUMERO_ENTERO",
  "NMERO_DECIMAL",
  "CORREO_ELECTRONICO",
  "CADENA_NO_ESPECIFICA",
  "Comilla",
  "URL",
  "PARENTESIS_APERTURA",
  "PARENTESIS_CIERRE",
  "SIGNO_MULTIPLICACION",
  "SIGNO_SUMA",
  "SIGNO_RESTA",
  "PUNTO_COMA",
  "SIGNO_IGUAL",
  "DOS_PUNTOS",
  "COMA",
  "LINEA_DIVISORA",
  "INICIO_ETIQUETA",
  "FINAL_ETIQUETA",
  "SALTO_LINEA",
  "INICO_DIALOGO",
  "FINAL_DIALOGO",
  "INICIO_PARRAFO",
  "FINAL_PARRAFO",
  "INICIO_ELEMENTO_LISTA",
  "FINAL_ELEMENTO_LISTA",
  "INICIO_MENU",
  "FINAL_MENU"
  };
}

